name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Setup submodules
      run: |
        git submodule update --init --recursive

    - name: Run tests
      run: |
        make test

    - name: Run coverage
      run: |
        make coverage

    - name: Lint code
      run: |
        make lint

    - name: Publish coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
